### PR TITLE
Add get_schools()

### LINKED ISSUE #33: Add support for national register of schools
See API definition [here](https://data-nsr.udir.no/swagger/index.html).

### PR DESCRIPTION
**Pull request by Aeilert**
@ohjakobsen 
cc: @ACEriksen 

Here is the suggested implementation for NSR. I'm not totally convinced by my attempt to add three endpoints into a single function, as well as the default option being to retrieve all the data. I think the pro arguments for this solution are 1) the endpoints do return the same content, 2) it is user friendly to have only one function and 3) "all" is probably the most logical default option. But open to other suggestions, e.g. to require the user to explicitly ask for all the data.  

Closes #33

### CODE REVIEW

**Comment by ohjakobsen** [comment]
Actually, from a frist code review (without too much testing, I admit), my conclusion is that this is a good first stab at a function for using this API. I'm not too keen on fetching all schools by default, but given that the API does not complain, and returns a 200, this should not be too big of a problem.

I agree that using one function instead of three is more user-friendly. I'm not sure if it is very user friendly to use two arguments where one must be named in order to use the function with either county codes or municipality codes (although there are plenty of examples of R functions with this set up). County codes will _always_ consist of two numbers with a leading zero, and municipality codes will _always_ consist of four numbers with a leading zero. From the input, we could easily infer if the user has provides county codes or municipality codes.

**Comment by Aeilert** [comment]
> Actually, from a frist code review (without too much testing, I admit), my conclusion is that this is a good first stab at a function for using this API. I'm not too keen on fetching all schools by default, but given that the API does not complain, and returns a 200, this should not be too big of a problem.
> 
> I agree that using one function instead of three is more user-friendly. I'm not sure if it is very user friendly to use two arguments where one must be named in order to use the function with either county codes or municipality codes (although there are plenty of examples of R functions with this set up). County codes will _always_ consist of two numbers with a leading zero, and municipality codes will _always_ consist of four numbers with a leading zero. From the input, we could easily infer if the user has provides county codes or municipality codes.

Thanks @ohjakobsen! I had many of the same thoughts. Regarding the last bit: The reason I chose two arguments is because I think it is easier to validate the user input and ensure that the response is correct. The API in question has very little validation on its own. E.g. requesting `/enheter/kommune` with a two digit code will often give you a 200 response, but with the wrong content. 

Imagine for example that a user queries schools by municipality with `get_schools(x = c(4601, 1101, 11, 1103)`, where for some reason the third value is a typo or mistake in the data. This could be a bit difficult to catch since a two-digit code is generally a valid input for `x`. I admit that this is a somewhat edge case, but there is a real risk of returning data that would be unexpexcted by the user. Particularly when binding to a data.frame the responses look quite messy. I thus think we have the following options: 

1. The current approach:

   * **Pro:** Clear distinction is what is being requested. Users only need to specify one argument. Simple validation handling. 
   * **Con**: Users need to learn two arguments (`county` and `municipality` ) 
  
2. `get_schools(x, ...)` which forwards all two-digit codes to `/enheter/fylke` and all four-digit codes to `/enheter/kommuner`: 

   * **Pro:** Users only need to learn _and_ specify one argument. Added feature of handling counties and muncipalites in the same function call.
   * **Con:** Not a clear distinction in what is bundled together in the output. 

3.  `get_schools(x, type = c('municipality', 'county'), ...)`: 

   * **Pro:** Clear distinction is what is being requested. Users only need to specify one argument. Simple validation handling.  
   * **Con:** Users need to specify two arguments. 

I'm leaning towards option 1. or 3. here, but certainly open to other ideas. @ohjakobsen @ACEriksen

**Review by ohjakobsen — CHANGES_REQUESTED** [review]
Some comments on the code in addition to the more broader discussion on the main input argument to the function.

**Comment by Aeilert** [comment]
Thanks @ohjakobsen. I have been thinking a bit about this, and I agree that option 2 is perhaps the best option _if_ we manage to handle the validation properly. I can work out a new suggestion.

**Comment by Aeilert** [comment]
@ohjakobsen: The code has now been updated to align with option 2. I also added functionality to handle 1 and 3 digit codes.

**Comment by ohjakobsen** [comment]
I think this is good for now. Support for both county and municipality codes with an `x` argument works well. I've done a couple of changes to the function documentation, and will approve this PR:

**Review by ohjakobsen — APPROVED** [review]

**Comment by Aeilert** [comment]
Thanks @ohjakobsen . Merging this.

**Pull request merged**
