### PR TITLE
Add get_kindergartens

### LINKED ISSUE #34: Add support for national register of kindergartens
See API definition [here](https://data-nbr.udir.no/swagger/index.html)

### PR DESCRIPTION
**Pull request by Aeilert**
Closes #34

### CODE REVIEW

**Review by ohjakobsen — CHANGES_REQUESTED** [review]
The functionality is great, but I suggest that we merge the utility functions in `nsr-utils.R` and `nbr-utils.R`. These functions are more or less identical, and should be written more DRY.

**Comment by ohjakobsen** [comment]
@Aeilert Would it be possible to close this during this week?

**Comment by Aeilert** [comment]
@ohjakobsen: I've updated the PR with a set of common utils functions for NSR and NBR.

**Review by ohjakobsen — APPROVED** [review]
I suggest a squash commit to the main branch

**Pull request merged**
